project:
  type: website
  output-dir: docs

website:
  title: "Divorce & Crime Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorial.qmd
        text: Tutorial
      - href: documentation.qmd
        text: Documentation
      - href: writeup.qmd
        text: Write Up

format:
  html:
    theme: cosmo
    toc: true
